// Code generated by Canoto. DO NOT EDIT.

package examples

import (
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that "unicode/utf8" is imported without error
var _ = utf8.ValidString

const (
	canoto__LargestFieldNumber__Int32__tag = "\xf8\xff\xff\xff\x0f" // canoto.Tag(536870911, canoto.Varint)

	canoto__LargestFieldNumber__Int32__tag__size = len(canoto__LargestFieldNumber__Int32__tag)
)

type canotoData_LargestFieldNumber struct {
	size int
}

func (c *LargestFieldNumber) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(&r)
}

func (c *LargestFieldNumber) UnmarshalCanotoFrom(r *canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(r) {
		field, wireType, err := canoto.ReadTag(r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 536870911:
			if wireType != canoto.Varint {
				return canoto.ErrInvalidWireType
			}
			c.Int32, err = canoto.ReadInt[int32](r)
			if err != nil {
				return err
			}
			if c.Int32 == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

func (c *LargestFieldNumber) ValidCanoto() bool {
	return true
}

func (c *LargestFieldNumber) CalculateCanotoSize() int {
	c.canotoData.size = 0
	if c.Int32 != 0 {
		c.canotoData.size += canoto__LargestFieldNumber__Int32__tag__size + canoto.SizeInt(c.Int32)
	}
	return c.canotoData.size
}

func (c *LargestFieldNumber) CachedCanotoSize() int {
	return c.canotoData.size
}

func (c *LargestFieldNumber) MarshalCanoto() []byte {
	w := canoto.Writer{
		B: make([]byte, 0, c.CalculateCanotoSize()),
	}
	c.MarshalCanotoInto(&w)
	return w.B
}

func (c *LargestFieldNumber) MarshalCanotoInto(w *canoto.Writer) {
	if c.Int32 != 0 {
		canoto.Append(w, canoto__LargestFieldNumber__Int32__tag)
		canoto.AppendInt(w, c.Int32)
	}
}
