package generate

import (
	"encoding/hex"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"os"
	"strings"

	"github.com/StephenButtolph/canoto"
)

const (
	goExtension     = ".go"
	canotoExtension = ".canoto.go"

	goTestExtension     = "_test.go"
	canotoTestExtension = ".canoto_test.go"

	defaultCanotoImporter = "canoto."
)

var errNonGoExtension = errors.New("file must be a go file")

// Canoto generates the canoto serialization logic for the provided file.
func Canoto(
	inputFilePath string,
	canotoImport string,
	internal bool,
) error {
	var outputFilePath string
	switch {
	case strings.HasSuffix(inputFilePath, goTestExtension):
		outputFilePath = inputFilePath[:len(inputFilePath)-len(goTestExtension)] + canotoTestExtension
	case strings.HasSuffix(inputFilePath, goExtension):
		outputFilePath = inputFilePath[:len(inputFilePath)-len(goExtension)] + canotoExtension
	default:
		return errNonGoExtension
	}

	// Create a new parser
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, inputFilePath, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	packageName, messages, err := parse(fs, f, canotoImport, internal)
	if err != nil {
		return err
	}
	if len(messages) == 0 {
		return nil
	}

	outputFile, err := os.Create(outputFilePath)
	if err != nil {
		return err
	}
	defer outputFile.Close()

	return writeCanoto(outputFile, inputFilePath, packageName, messages, canotoImport, internal)
}

func writeCanoto(
	w io.Writer,
	source string,
	packageName string,
	messages []message,
	canotoImport string,
	internal bool,
) error {
	const fileTemplate = `// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto ${version}
// source: ${source}

package ${package}

import (
	"io"
	"sync/atomic"
	"unicode/utf8"
${canotoImport})

// Ensure that unused imports do not error
var (
	_ atomic.Int64

	_ = io.ErrUnexpectedEOF
	_ = utf8.ValidString
)
`
	// Only include the import for canoto if this is not an internal file.
	if internal {
		canotoImport = ""
	} else {
		canotoImport = fmt.Sprintf("\n\t%s\n", canotoImport)
	}
	err := writeTemplate(w, fileTemplate, map[string]string{
		"version":      canoto.Version,
		"source":       source,
		"package":      packageName,
		"canotoImport": canotoImport,
	})
	if err != nil {
		return err
	}

	var selector string
	if !internal {
		selector = defaultCanotoImporter
	}
	for _, m := range messages {
		if err := writeStruct(w, m, selector); err != nil {
			return err
		}
	}
	return nil
}

func writeStruct(w io.Writer, m message, canotoSelector string) error {
	const structTemplate = `
const (
${tagConstants})

type canotoData_${structName} struct {
${sizeCache}${oneOfCache}}

// MakeCanoto creates a new empty value.
func (*${structName}${generics}) MakeCanoto() *${structName}${generics} {
	return new(${structName}${generics})
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *${structName}${generics}) UnmarshalCanoto(bytes []byte) error {
	r := ${selector}Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a canoto.Reader. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *${structName}${generics}) UnmarshalCanotoFrom(r ${selector}Reader) error {
	// Zero the struct before unmarshaling.
	*c = ${structName}${generics}{}
	c.canotoData.size${storePrefix}len(r.B)${storeSuffix}

	var minField uint32
	for ${selector}HasNext(&r) {
		field, wireType, err := ${selector}ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return ${selector}ErrInvalidFieldOrder
		}

		switch field {
${unmarshal}		default:
			return ${selector}ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *${structName}${generics}) ValidCanoto() bool {
	if c == nil {
		return true
	}
${validOneOf}${valid}	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.${concurrencyWarning}
func (c *${structName}${generics}) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var (
${sizeVars}	)
${size}${assignSizeVars}}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *${structName}${generics}) CachedCanotoSize() int {
	if c == nil {
		return 0
	}
	return int(c.canotoData.size${load})
}${oneOfCacheAccessors}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.${concurrencyWarning}
func (c *${structName}${generics}) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := ${selector}Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a canoto.Writer and returns the
// resulting canoto.Writer. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.${concurrencyWarning}
func (c *${structName}${generics}) MarshalCanotoInto(w ${selector}Writer) ${selector}Writer {
	if c == nil {
		return w
	}
${marshal}	return w
}
`

	var (
		load               string
		storePrefix        = " = "
		storeSuffix        string
		concurrencyWarning = `
//
// It is not safe to call this function concurrently.`
	)
	if m.useAtomic {
		load = ".Load()"
		storePrefix = ".Store(int64("
		storeSuffix = "))"
		concurrencyWarning = ""
	}
	return writeTemplate(w, structTemplate, map[string]string{
		"tagConstants":        makeTagConstants(m),
		"structName":          m.name,
		"generics":            makeGenerics(m),
		"selector":            canotoSelector,
		"sizeCache":           makeSizeCache(m),
		"oneOfCache":          makeOneOfCache(m),
		"unmarshal":           makeUnmarshal(m),
		"validOneOf":          makeValidOneOf(m),
		"valid":               makeValid(m),
		"concurrencyWarning":  concurrencyWarning,
		"sizeVars":            makeSizeVars(m),
		"size":                makeSize(m),
		"assignSizeVars":      makeAssignSizeVars(m),
		"load":                load,
		"storePrefix":         storePrefix,
		"storeSuffix":         storeSuffix,
		"oneOfCacheAccessors": makeOneOfCacheAccessors(m),
		"marshal":             makeMarshal(m),
	})
}

func makeGenerics(m message) string {
	if m.numTypes == 0 {
		return ""
	}

	var s strings.Builder
	_, _ = s.WriteString("[")
	for i := range m.numTypes {
		if i != 0 {
			_, _ = s.WriteString(", ")
		}
		_, _ = s.WriteString(fmt.Sprintf("T%d", i+1))
	}
	_, _ = s.WriteString("]")
	return s.String()
}

func makeTagConstants(m message) string {
	const tagSizeOverhead = len("canoto______tag")
	var (
		largestTagConstSize int
		largestTagSize      int
	)
	for _, f := range m.fields {
		tagConstSize := tagSizeOverhead + len(m.canonicalizedName) + len(f.canonicalizedName)
		largestTagConstSize = max(largestTagConstSize, tagConstSize)

		wireType := f.canotoType.WireType()
		tagBytes := canoto.Tag(f.fieldNumber, wireType)
		tagSize := 2 + 4*len(tagBytes)
		largestTagSize = max(largestTagSize, tagSize)
	}

	var (
		template = fmt.Sprintf("\t%%-%ds = %%-%ds // canoto.Tag(%%d, canoto.%%s)\n",
			largestTagConstSize,
			largestTagSize,
		)
		s strings.Builder
	)
	for _, f := range m.fields {
		tag := fmt.Sprintf("canoto__%s__%s__tag", m.canonicalizedName, f.canonicalizedName)

		var tagString strings.Builder
		_, _ = tagString.WriteString(`"`)
		wireType := f.canotoType.WireType()
		tagBytes := canoto.Tag(f.fieldNumber, wireType)
		tagHex := hex.EncodeToString(tagBytes)
		for i := 0; i < len(tagHex); i += 2 {
			_, _ = fmt.Fprintf(&tagString, "\\x%s", tagHex[i:i+2])
		}
		_, _ = tagString.WriteString(`"`)

		_, _ = fmt.Fprintf(&s, template, tag, &tagString, f.fieldNumber, wireType)
	}
	return s.String()
}

func makeSizeCache(m message) string {
	const (
		sizeVar    = "size"
		sizeSuffix = "Size"
	)
	largestNameSize := len(sizeVar)
	for _, f := range m.fields {
		if !f.canotoType.IsRepeated() || !f.canotoType.IsVarint() {
			continue
		}

		largestNameSize = max(largestNameSize, len(f.name)+len(sizeSuffix))
	}

	sizeType := "int"
	if m.useAtomic {
		sizeType = "atomic.Int64"
	}

	var (
		s        strings.Builder
		template = fmt.Sprintf("\t%%-%ds %s\n", largestNameSize, sizeType)
	)
	_, _ = fmt.Fprintf(&s, template, sizeVar)
	for _, f := range m.fields {
		if !f.canotoType.IsRepeated() || !f.canotoType.IsVarint() {
			continue
		}

		_, _ = fmt.Fprintf(&s, template, f.name+sizeSuffix)
	}
	return s.String()
}

func makeOneOfCache(m message) string {
	oneOfs := m.OneOfs()
	if len(oneOfs) == 0 {
		return ""
	}

	var largestNameSize int
	for _, oneOf := range oneOfs {
		largestNameSize = max(largestNameSize, len(oneOf))
	}

	oneOfType := "uint32"
	if m.useAtomic {
		oneOfType = "atomic.Uint32"
	}

	const oneOfSuffix = "OneOf"
	var (
		template = fmt.Sprintf("\t%%-%ds %s\n", largestNameSize+len(oneOfSuffix), oneOfType)
		s        strings.Builder
	)
	_, _ = s.WriteString("\n")
	for _, oneOf := range oneOfs {
		_, _ = fmt.Fprintf(&s, template, oneOf+oneOfSuffix)
	}
	return s.String()
}

func makeUnmarshal(m message) string {
	const (
		intTemplate = `		case ${fieldNumber}:
			if wireType != ${selector}${wireType} {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			if err := ${selector}Read${suffix}(&r, &c.${fieldName}); err != nil {
				return err
			}
			if ${selector}IsZero(c.${fieldName}) {
				return ${selector}ErrZeroValue
			}
`
		repeatedFixedSizeTemplate = `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Verify the length of the packed field bytes.
			numMsgBytes := uint(len(msgBytes))
			if numMsgBytes == 0 {
				return ${selector}ErrZeroValue
			}
			if numMsgBytes%${selector}Size${suffix} != 0 {
				return ${selector}ErrInvalidLength
			}

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, int(numMsgBytes/${selector}Size${suffix}))
			for i := range c.${fieldName} {
				if err := ${selector}Read${suffix}(&r, &c.${fieldName}[i]); err != nil {
					return err
				}
			}
			r.B = remainingBytes
`
		fixedRepeatedFixedSizeTemplate = `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			for i := range &c.${fieldName} {
				if err := ${selector}Read${suffix}(&r, &(&c.${fieldName})[i]); err != nil {
					return err
				}
			}
			if ${selector}HasNext(&r) {
				return io.ErrUnexpectedEOF
			}
			if ${selector}IsZero(c.${fieldName}) {
				return ${selector}ErrZeroValue
			}
			r.B = remainingBytes
`
		bytesTemplate = `		case ${fieldNumber}:
			if wireType != ${selector}${wireType} {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			if err := ${selector}Read${suffix}(&r, &c.${fieldName}); err != nil {
				return err
			}
			if len(c.${fieldName}) == 0 {
				return ${selector}ErrZeroValue
			}
`
		repeatedBytesTemplate = `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Skip the first entry because we have already stripped the tag.
			remainingBytes := r.B
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			if err := ${selector}ReadBytes(&r, new([]byte)); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := ${selector}CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}
			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, countMinus1+1)

			// Read the first entry manually because the tag is still already
			// stripped.
			r.B = remainingBytes
			if err := ${selector}Read${suffix}(&r, &c.${fieldName}[0]); err != nil {
				return err
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				if err := ${selector}Read${suffix}(&r, &c.${fieldName}[1+i]); err != nil {
					return err
				}
			}
`
		fixedRepeatedBytes = `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			if err := ${selector}Read${suffix}(&r, &(&c.${fieldName})[0]); err != nil {
				return err
			}

			// Read the rest of the entries, stripping the tag each time.
			isZero := len((&c.${fieldName})[0]) == 0
			const numToRead = uint(len(c.${fieldName}) - 1)
			for i := range numToRead {
				if !${selector}HasPrefix(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag) {
					return ${selector}ErrUnknownField
				}
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				if err := ${selector}Read${suffix}(&r, &(&c.${fieldName})[1+i]); err != nil {
					return err
				}
				isZero = isZero && len((&c.${fieldName})[1+i]) == 0
			}
			if isZero {
				return ${selector}ErrZeroValue
			}
`
	)
	return writeMessage(m, messageTemplate{
		ints: typeTemplate{
			single: intTemplate,
			repeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return ${selector}ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, ${selector}CountInts(msgBytes))
			for i := range c.${fieldName} {
				if err := ${selector}Read${suffix}(&r, &c.${fieldName}[i]); err != nil {
					return err
				}
			}
			if ${selector}HasNext(&r) {
				return ${selector}ErrInvalidLength
			}
			r.B = remainingBytes
			c.canotoData.${fieldName}Size${storePrefix}len(msgBytes)${storeSuffix}
`,
			fixedRepeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the packed field bytes.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Read each value from the packed field bytes into the array.
			remainingBytes := r.B
			r.B = msgBytes
			for i := range &c.${fieldName} {
				if err := ${selector}Read${suffix}(&r, &(&c.${fieldName})[i]); err != nil {
					return err
				}
			}
			if ${selector}HasNext(&r) {
				return io.ErrUnexpectedEOF
			}
			if ${selector}IsZero(c.${fieldName}) {
				return ${selector}ErrZeroValue
			}
			r.B = remainingBytes
			c.canotoData.${fieldName}Size${storePrefix}len(msgBytes)${storeSuffix}
`,
		},
		fints: typeTemplate{
			single:        intTemplate,
			repeated:      repeatedFixedSizeTemplate,
			fixedRepeated: fixedRepeatedFixedSizeTemplate,
		},
		bools: typeTemplate{
			single:        intTemplate,
			repeated:      repeatedFixedSizeTemplate,
			fixedRepeated: fixedRepeatedFixedSizeTemplate,
		},
		strings: typeTemplate{
			single:        bytesTemplate,
			repeated:      repeatedBytesTemplate,
			fixedRepeated: fixedRepeatedBytes,
		},
		bytesTemplate:         bytesTemplate,
		repeatedBytesTemplate: repeatedBytesTemplate,
		fixedBytesTemplate: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			const (
				expectedLength      = len(c.${fieldName})
				expectedLengthInt64 = int64(expectedLength)
			)
			var length int64
			if err := ${selector}ReadInt(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthInt64 {
				return ${selector}ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.${fieldName})[:], r.B)
			if ${selector}IsZero(c.${fieldName}) {
				return ${selector}ErrZeroValue
			}
			r.B = r.B[expectedLength:]
`,
		repeatedFixedBytesTemplate: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			const (
				expectedLength      = len(c.${fieldName}[0])
				expectedLengthInt64 = int64(expectedLength)
			)

			// Read the first entry manually because the tag is already
			// stripped.
			var length int64
			if err := ${selector}ReadInt(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthInt64 {
				return ${selector}ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			firstEntry := r.B[:expectedLength]
			r.B = r.B[expectedLength:]

			// Count the number of additional entries after the first entry.
			countMinus1, err := ${selector}CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, countMinus1+1)
			copy((&c.${fieldName}[0])[:], firstEntry)

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				if err := ${selector}ReadInt(&r, &length); err != nil {
					return err
				}
				if length != expectedLengthInt64 {
					return ${selector}ErrInvalidLength
				}
				if expectedLength > len(r.B) {
					return io.ErrUnexpectedEOF
				}

				copy((&c.${fieldName}[1+i])[:], r.B)
				r.B = r.B[expectedLength:]
			}
`,
		fixedRepeatedBytesTemplate: fixedRepeatedBytes,
		fixedRepeatedFixedBytesTemplate: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			const (
				expectedLength      = len(c.${fieldName}[0])
				expectedLengthInt64 = int64(expectedLength)
			)

			// Read the first entry manually because the tag is already
			// stripped.
			var length int64
			if err := ${selector}ReadInt(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthInt64 {
				return ${selector}ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&(&c.${fieldName})[0])[:], r.B)
			r.B = r.B[expectedLength:]

			// Read the rest of the entries, stripping the tag each time.
			const numToRead = uint(len(c.${fieldName}) - 1)
			for i := range numToRead {
				if !${selector}HasPrefix(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag) {
					return ${selector}ErrUnknownField
				}
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]

				if err := ${selector}ReadInt(&r, &length); err != nil {
					return err
				}
				if length != expectedLengthInt64 {
					return ${selector}ErrInvalidLength
				}
				if expectedLength > len(r.B) {
					return io.ErrUnexpectedEOF
				}

				copy((&(&c.${fieldName})[1+i])[:], r.B)
				r.B = r.B[expectedLength:]
			}
			if ${selector}IsZero(c.${fieldName}) {
				return ${selector}ErrZeroValue
			}
`,
		values: typeTemplate{
			single: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return ${selector}ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			if err := ${genericTypeCast}(&c.${fieldName}).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
`,
			repeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := ${selector}CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := ${genericTypeCast}(&c.${fieldName}[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := ${genericTypeCast}(&c.${fieldName}[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
`,
			fixedRepeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			isZero := len(msgBytes) == 0
			if !isZero {
				remainingBytes := r.B
				r.B = msgBytes
				if err := ${genericTypeCast}(&c.${fieldName}[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			const numToRead = uint(len(c.${fieldName}) - 1)
			for i := range numToRead {
				if !${selector}HasPrefix(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag) {
					return ${selector}ErrUnknownField
				}
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := ${genericTypeCast}(&c.${fieldName}[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
				isZero = false
			}
			if isZero {
				return ${selector}ErrZeroValue
			}
`,
		},
		pointers: typeTemplate{
			single: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return ${selector}ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = ${selector}MakePointer(c.${fieldName})
			if err := ${genericTypeCast}(c.${fieldName}).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
`,
			repeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := ${selector}CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[0] = ${selector}MakePointer(c.${fieldName}[0])
				if err := ${genericTypeCast}(c.${fieldName}[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[1+i] = ${selector}MakePointer(c.${fieldName}[1+i])
				if err := ${genericTypeCast}(c.${fieldName}[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
`,
			fixedRepeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			c.${fieldName}[0] = nil
			isZero := len(msgBytes) == 0
			if !isZero {
				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[0] = ${selector}MakePointer(c.${fieldName}[0])
				if err := ${genericTypeCast}(c.${fieldName}[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			const numToRead = uint(len(c.${fieldName}) - 1)
			for i := range numToRead {
				if !${selector}HasPrefix(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag) {
					return ${selector}ErrUnknownField
				}
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					c.${fieldName}[1+i] = nil
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[1+i] = ${selector}MakePointer(c.${fieldName}[1+i])
				if err := ${genericTypeCast}(c.${fieldName}[1+i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
				isZero = false
			}
			if isZero {
				return ${selector}ErrZeroValue
			}
`,
		},
		fields: typeTemplate{
			single: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return ${selector}ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = c.${fieldName}.MakeCanoto()
			if err := c.${fieldName}.UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
`,
			repeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := ${selector}CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = ${selector}MakeSlice(c.${fieldName}, countMinus1+1)
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[0] = c.${fieldName}[0].MakeCanoto()
				if err := c.${fieldName}[0].UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range countMinus1 {
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[1+i] = c.${fieldName}[1+i].MakeCanoto()
				if err := c.${fieldName}[1+i].UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
`,
			fixedRepeated: `		case ${fieldNumber}:
			if wireType != ${selector}Len {
				return ${selector}ErrUnexpectedWireType
			}${unmarshalOneOf}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			c.${fieldName}[0] = ${selector}Zero(c.${fieldName}[0])
			isZero := len(msgBytes) == 0
			if !isZero {
				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[0] = c.${fieldName}[0].MakeCanoto()
				if err := c.${fieldName}[0].UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			const numToRead = uint(len(c.${fieldName}) - 1)
			for i := range numToRead {
				if !${selector}HasPrefix(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag) {
					return ${selector}ErrUnknownField
				}
				r.B = r.B[len(canoto__${escapedStructName}__${escapedFieldName}__tag):]
				r.Unsafe = true
				if err := ${selector}ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					c.${fieldName}[1+i] = ${selector}Zero(c.${fieldName}[1+i])
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				c.${fieldName}[1+i] = c.${fieldName}[1+i].MakeCanoto()
				if err := c.${fieldName}[1+i].UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
				isZero = false
			}
			if isZero {
				return ${selector}ErrZeroValue
			}
`,
		},
	})
}

func makeValidOneOf(m message) string {
	oneOfs := m.OneOfs()
	if len(oneOfs) == 0 {
		return ""
	}

	var largestNameSize int
	for _, oneOf := range oneOfs {
		largestNameSize = max(largestNameSize, len(oneOf))
	}

	const oneOfSuffix = "OneOf"
	var (
		template = fmt.Sprintf("\t\t%%-%ds uint32\n", largestNameSize+len(oneOfSuffix))
		s        strings.Builder
	)
	_, _ = s.WriteString("\tvar (\n")
	for _, oneOf := range oneOfs {
		_, _ = fmt.Fprintf(&s, template, oneOf+oneOfSuffix)
	}
	_, _ = s.WriteString("\t)\n")

	const (
		functionTemplate = `	if !${selector}IsZero(c.${fieldName}) {
		if ${oneOf}OneOf != 0 {
			return false
		}
		${oneOf}OneOf = ${fieldNumber}
	}
`
		repeatedTemplate = `	if len(c.${fieldName}) != 0 {
		if ${oneOf}OneOf != 0 {
			return false
		}
		${oneOf}OneOf = ${fieldNumber}
	}
`
	)
	var (
		primitiveTemplate = typeTemplate{
			single:        functionTemplate,
			repeated:      repeatedTemplate,
			fixedRepeated: functionTemplate,
		}
		t = messageTemplate{
			ints:    primitiveTemplate,
			fints:   primitiveTemplate,
			bools:   primitiveTemplate,
			strings: primitiveTemplate,

			bytesTemplate:              repeatedTemplate,
			repeatedBytesTemplate:      repeatedTemplate,
			fixedBytesTemplate:         functionTemplate,
			repeatedFixedBytesTemplate: repeatedTemplate,
			fixedRepeatedBytesTemplate: `	{
		isZero := true
		for _, v := range c.${fieldName} {
			if len(v) != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			if ${oneOf}OneOf != 0 {
				return false
			}
			${oneOf}OneOf = ${fieldNumber}
		}
	}
`,
			fixedRepeatedFixedBytesTemplate: functionTemplate,

			values: typeTemplate{
				single: `	if ${genericTypeCast}(&c.${fieldName}).CalculateCanotoCache(); ${genericTypeCast}(&c.${fieldName}).CachedCanotoSize() != 0 {
		if ${oneOf}OneOf != 0 {
			return false
		}
		${oneOf}OneOf = ${fieldNumber}
	}
`,
				repeated: repeatedTemplate,
				fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			if ${genericTypeCast}(&c.${fieldName}[i]).CalculateCanotoCache(); ${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			if ${oneOf}OneOf != 0 {
				return false
			}
			${oneOf}OneOf = ${fieldNumber}
		}
	}
`,
			},
			pointers: typeTemplate{
				single: `	if c.${fieldName} != nil {
		${genericTypeCast}(c.${fieldName}).CalculateCanotoCache()
		if ${genericTypeCast}(c.${fieldName}).CachedCanotoSize() != 0 {
			if ${oneOf}OneOf != 0 {
				return false
			}
			${oneOf}OneOf = ${fieldNumber}
		}
	}
`,
				repeated: repeatedTemplate,
				fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			if c.${fieldName}[i] == nil {
				continue
			}
			c.${fieldName}[i].CalculateCanotoCache()
			if ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			if ${oneOf}OneOf != 0 {
				return false
			}
			${oneOf}OneOf = ${fieldNumber}
		}
	}
`,
			},
			fields: typeTemplate{
				single: `	c.${fieldName}.CalculateCanotoCache()
	if c.${fieldName}.CachedCanotoSize() != 0 {
		if ${oneOf}OneOf != 0 {
			return false
		}
		${oneOf}OneOf = ${fieldNumber}
	}
`,
				repeated: repeatedTemplate,
				fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			c.${fieldName}[i].CalculateCanotoCache()
			if c.${fieldName}[i].CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			if ${oneOf}OneOf != 0 {
				return false
			}
			${oneOf}OneOf = ${fieldNumber}
		}
	}
`,
			},
		}
	)

	for _, f := range m.fields {
		if f.oneOfName == "" {
			continue
		}

		_ = writeField(&s, f, t)
	}
	return s.String()
}

func makeValid(m message) string {
	return writeMessage(m, messageTemplate{
		strings: typeTemplate{
			single: `	if !utf8.ValidString(string(c.${fieldName})) {
		return false
	}
`,
			repeated: `	for _, v := range c.${fieldName} {
		if !utf8.ValidString(string(v)) {
			return false
		}
	}
`,
			fixedRepeated: `	for _, v := range &c.${fieldName} {
		if !utf8.ValidString(string(v)) {
			return false
		}
	}
`,
		},
		values: typeTemplate{
			single: `	if !${genericTypeCast}(&c.${fieldName}).ValidCanoto() {
		return false
	}
`,
			repeated: `	for i := range c.${fieldName} {
		if !${genericTypeCast}(&c.${fieldName}[i]).ValidCanoto() {
			return false
		}
	}
`,
			fixedRepeated: `	for i := range &c.${fieldName} {
		if !${genericTypeCast}(&(&c.${fieldName})[i]).ValidCanoto() {
			return false
		}
	}
`,
		},
		pointers: typeTemplate{
			single: `	if c.${fieldName} != nil && !${genericTypeCast}(c.${fieldName}).ValidCanoto() {
		return false
	}
`,
			repeated: `	for i := range c.${fieldName} {
		if c.${fieldName}[i] != nil && !${genericTypeCast}(c.${fieldName}[i]).ValidCanoto() {
			return false
		}
	}
`,
			fixedRepeated: `	for i := range &c.${fieldName} {
		if (&c.${fieldName})[i] != nil && !${genericTypeCast}((&c.${fieldName})[i]).ValidCanoto() {
			return false
		}
	}
`,
		},
		fields: typeTemplate{
			single: `	if !c.${fieldName}.ValidCanoto() {
		return false
	}
`,
			repeated: `	for i := range c.${fieldName} {
		if !c.${fieldName}[i].ValidCanoto() {
			return false
		}
	}
`,
			fixedRepeated: `	for i := range &c.${fieldName} {
		if !(&c.${fieldName})[i].ValidCanoto() {
			return false
		}
	}
`,
		},
	})
}

func makeSizeVars(m message) string {
	oneOfs := m.OneOfs()
	const (
		sizeName    = "size"
		oneOfSuffix = "OneOf"
	)
	largestNameSize := len(sizeName)
	for _, oneOf := range oneOfs {
		largestNameSize = max(largestNameSize, len(oneOf)+len(oneOfSuffix))
	}

	var (
		sizeTemplate  = fmt.Sprintf("\t\t%%-%ds int\n", largestNameSize)
		oneOfTemplate = fmt.Sprintf("\t\t%%-%ds uint32\n", largestNameSize)
		s             strings.Builder
	)
	_, _ = fmt.Fprintf(&s, sizeTemplate, sizeName)
	for _, oneOf := range oneOfs {
		_, _ = fmt.Fprintf(&s, oneOfTemplate, oneOf+oneOfSuffix)
	}
	return s.String()
}

func makeSize(m message) string {
	const (
		fixedSizeTemplate = `	if !${selector}IsZero(c.${fieldName}) {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}Size${suffix}${sizeOneOf}
	}
`
		repeatedFixedSizeTemplate = `	if num := len(c.${fieldName}); num != 0 {
		fieldSize := num * ${selector}Size${suffix}
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`
		fixedRepeatedFixedSizeTemplate = `	if !${selector}IsZero(c.${fieldName}) {
		const fieldSize = len(c.${fieldName}) * ${selector}Size${suffix}
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + fieldSize + ${selector}SizeInt(int64(fieldSize))${sizeOneOf}
	}
`
		bytesTemplate = `	if len(c.${fieldName}) != 0 {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes(c.${fieldName})${sizeOneOf}
	}
`
		repeatedBytesTemplate = `	for _, v := range c.${fieldName} {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes(v)${sizeOneOf}
	}
`
	)
	return writeMessage(m, messageTemplate{
		ints: typeTemplate{
			single: `	if !${selector}IsZero(c.${fieldName}) {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}Size${suffix}(c.${fieldName})${sizeOneOf}
	}
`,
			repeated: `	if len(c.${fieldName}) != 0 {
		var fieldSize int
		for _, v := range c.${fieldName} {
			fieldSize += ${selector}Size${suffix}(v)
		}
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize
		c.canotoData.${fieldName}Size${storePrefix}fieldSize${storeSuffix}${sizeOneOf}
	}
`,
			fixedRepeated: `	if !${selector}IsZero(c.${fieldName}) {
		var fieldSize int
		for _, v := range &c.${fieldName} {
			fieldSize += ${selector}Size${suffix}(v)
		}
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize
		c.canotoData.${fieldName}Size${storePrefix}fieldSize${storeSuffix}${sizeOneOf}
	}
`,
		},
		fints: typeTemplate{
			single:        fixedSizeTemplate,
			repeated:      repeatedFixedSizeTemplate,
			fixedRepeated: fixedRepeatedFixedSizeTemplate,
		},
		bools: typeTemplate{
			single:        fixedSizeTemplate,
			repeated:      repeatedFixedSizeTemplate,
			fixedRepeated: fixedRepeatedFixedSizeTemplate,
		},
		strings: typeTemplate{
			single:   bytesTemplate,
			repeated: repeatedBytesTemplate,
			fixedRepeated: `	if !${selector}IsZero(c.${fieldName}) {
		for _, v := range &c.${fieldName} {
			size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes(v)
		}${sizeOneOf}
	}
`,
		},
		bytesTemplate:         bytesTemplate,
		repeatedBytesTemplate: repeatedBytesTemplate,
		fixedBytesTemplate: `	if !${selector}IsZero(c.${fieldName}) {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes((&c.${fieldName})[:])${sizeOneOf}
	}
`,
		repeatedFixedBytesTemplate: `	if num := len(c.${fieldName}); num != 0 {
		fieldSize := len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes((&c.${fieldName}[0])[:])
		size += num * fieldSize${sizeOneOf}
	}
`,
		fixedRepeatedBytesTemplate: `	{
		isZero := true
		for _, v := range c.${fieldName} {
			if len(v) != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			for _, v := range c.${fieldName} {
				size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes(v)
			}${sizeOneOfIndent}
		}
	}
`,
		fixedRepeatedFixedBytesTemplate: `	if !${selector}IsZero(c.${fieldName}) {
		for i := range c.${fieldName} {
			size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeBytes((&(&c.${fieldName})[i])[:])
		}${sizeOneOf}
	}
`,
		values: typeTemplate{
			single: `	${genericTypeCast}(&c.${fieldName}).CalculateCanotoCache()
	if fieldSize := ${genericTypeCast}(&c.${fieldName}).CachedCanotoSize(); fieldSize != 0 {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`,
			repeated: `	for i := range c.${fieldName} {
		${genericTypeCast}(&c.${fieldName}[i]).CalculateCanotoCache()
		fieldSize := ${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize()
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`,
			fixedRepeated: `	{
		var (
			fieldSizeSum int
			totalSize    int
		)
		for i := range c.${fieldName} {
			${genericTypeCast}(&c.${fieldName}[i]).CalculateCanotoCache()
			fieldSize := ${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize()
			fieldSizeSum += fieldSize
			totalSize += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize
		}
		if fieldSizeSum != 0 {
			size += totalSize${sizeOneOfIndent}
		}
	}
`,
		},
		pointers: typeTemplate{
			single: `	if c.${fieldName} != nil {
		${genericTypeCast}(c.${fieldName}).CalculateCanotoCache()
		if fieldSize := ${genericTypeCast}(c.${fieldName}).CachedCanotoSize(); fieldSize != 0 {
			size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
		}
	}
`,
			repeated: `	for i := range c.${fieldName} {
		var fieldSize int
		if c.${fieldName}[i] != nil {
			${genericTypeCast}(c.${fieldName}[i]).CalculateCanotoCache()
			fieldSize = ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize()
		}
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`,
			fixedRepeated: `	{
		var (
			fieldSizeSum int
			totalSize    int
		)
		for i := range c.${fieldName} {
			var fieldSize int
			if c.${fieldName}[i] != nil {
				${genericTypeCast}(c.${fieldName}[i]).CalculateCanotoCache()
				fieldSize = ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize()
				fieldSizeSum += fieldSize
			}
			totalSize += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize
		}
		if fieldSizeSum != 0 {
			size += totalSize${sizeOneOfIndent}
		}
	}
`,
		},
		fields: typeTemplate{
			single: `	c.${fieldName}.CalculateCanotoCache()
	if fieldSize := c.${fieldName}.CachedCanotoSize(); fieldSize != 0 {
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`,
			repeated: `	for i := range c.${fieldName} {
		c.${fieldName}[i].CalculateCanotoCache()
		fieldSize := c.${fieldName}[i].CachedCanotoSize()
		size += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize${sizeOneOf}
	}
`,
			fixedRepeated: `	{
		var (
			fieldSizeSum int
			totalSize    int
		)
		for i := range c.${fieldName} {
			c.${fieldName}[i].CalculateCanotoCache()
			fieldSize := c.${fieldName}[i].CachedCanotoSize()
			fieldSizeSum += fieldSize
			totalSize += len(canoto__${escapedStructName}__${escapedFieldName}__tag) + ${selector}SizeInt(int64(fieldSize)) + fieldSize
		}
		if fieldSizeSum != 0 {
			size += totalSize${sizeOneOfIndent}
		}
	}
`,
		},
	})
}

func makeAssignSizeVars(m message) string {
	var s strings.Builder
	if m.useAtomic {
		s.WriteString("\tc.canotoData.size.Store(int64(size))\n")
	} else {
		s.WriteString("\tc.canotoData.size = size\n")
	}
	for _, oneOf := range m.OneOfs() {
		if m.useAtomic {
			_, _ = fmt.Fprintf(&s, "\tc.canotoData.%sOneOf.Store(%sOneOf)\n", oneOf, oneOf)
		} else {
			_, _ = fmt.Fprintf(&s, "\tc.canotoData.%sOneOf = %sOneOf\n", oneOf, oneOf)
		}
	}
	return s.String()
}

func makeOneOfCacheAccessors(m message) string {
	const template = `

// CachedWhichOneOf${oneOf} returns the previously calculated field number used
// to represent ${oneOf}.
//
// This field is cached by UnmarshalCanoto, UnmarshalCanotoFrom, and
// CalculateCanotoCache.
//
// If the field has not yet been cached, it will return 0.
//
// If the struct has been modified since the field was last cached, the returned
// field number may be incorrect.
func (c *${structName}${generics}) CachedWhichOneOf${oneOf}() uint32 {
	return c.canotoData.${oneOf}OneOf${load}
}`
	var (
		s        strings.Builder
		generics = makeGenerics(m)
		load     string
	)
	if m.useAtomic {
		load = ".Load()"
	}
	for _, oneOf := range m.OneOfs() {
		_ = writeTemplate(&s, template, map[string]string{
			"oneOf":      oneOf,
			"structName": m.name,
			"generics":   generics,
			"load":       load,
		})
	}
	return s.String()
}

func makeMarshal(m message) string {
	const (
		intTemplate = `	if !${selector}IsZero(c.${fieldName}) {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}Append${suffix}(&w, c.${fieldName})
	}
`
		repeatedFintTemplate = `	if num := len(c.${fieldName}); num != 0 {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(num*${selector}Size${suffix}))
		for _, v := range c.${fieldName} {
			${selector}Append${suffix}(&w, v)
		}
	}
`
		fixedRepeatedFintTemplate = `	if !${selector}IsZero(c.${fieldName}) {
		const fieldSize = len(c.${fieldName}) * ${selector}Size${suffix}
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(fieldSize))
		for _, v := range &c.${fieldName} {
			${selector}Append${suffix}(&w, v)
		}
	}
`
		bytesTemplate = `	if len(c.${fieldName}) != 0 {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendBytes(&w, c.${fieldName})
	}
`
		repeatedBytesTemplate = `	for _, v := range c.${fieldName} {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendBytes(&w, v)
	}
`
	)
	return writeMessage(m, messageTemplate{
		ints: typeTemplate{
			single: intTemplate,
			repeated: `	if len(c.${fieldName}) != 0 {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(c.canotoData.${fieldName}Size${load}))
		for _, v := range c.${fieldName} {
			${selector}Append${suffix}(&w, v)
		}
	}
`,
			fixedRepeated: `	if !${selector}IsZero(c.${fieldName}) {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(c.canotoData.${fieldName}Size${load}))
		for _, v := range &c.${fieldName} {
			${selector}Append${suffix}(&w, v)
		}
	}
`,
		},
		fints: typeTemplate{
			single:        intTemplate,
			repeated:      repeatedFintTemplate,
			fixedRepeated: fixedRepeatedFintTemplate,
		},
		bools: typeTemplate{
			single: `	if !${selector}IsZero(c.${fieldName}) {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendBool(&w, true)
	}
`,
			repeated:      repeatedFintTemplate,
			fixedRepeated: fixedRepeatedFintTemplate,
		},
		strings: typeTemplate{
			single:   bytesTemplate,
			repeated: repeatedBytesTemplate,
			fixedRepeated: `	if !${selector}IsZero(c.${fieldName}) {
		for _, v := range &c.${fieldName} {
			${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
			${selector}AppendBytes(&w, v)
		}
	}
`,
		},
		bytesTemplate:         bytesTemplate,
		repeatedBytesTemplate: repeatedBytesTemplate,
		fixedBytesTemplate: `	if !${selector}IsZero(c.${fieldName}) {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendBytes(&w, (&c.${fieldName})[:])
	}
`,
		repeatedFixedBytesTemplate: `	for i := range c.${fieldName} {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendBytes(&w, (&c.${fieldName}[i])[:])
	}
`,
		fixedRepeatedBytesTemplate: `	{
		isZero := true
		for _, v := range c.${fieldName} {
			if len(v) != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			for _, v := range c.${fieldName} {
				${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
				${selector}AppendBytes(&w, v)
			}
		}
	}
`,
		fixedRepeatedFixedBytesTemplate: `	if !${selector}IsZero(c.${fieldName}) {
		for i := range c.${fieldName} {
			${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
			${selector}AppendBytes(&w, (&(&c.${fieldName})[i])[:])
		}
	}
`,
		values: typeTemplate{
			single: `	if fieldSize := ${genericTypeCast}(&c.${fieldName}).CachedCanotoSize(); fieldSize != 0 {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(fieldSize))
		w = ${genericTypeCast}(&c.${fieldName}).MarshalCanotoInto(w)
	}
`,
			repeated: `	for i := range c.${fieldName} {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize()))
		w = ${genericTypeCast}(&c.${fieldName}[i]).MarshalCanotoInto(w)
	}
`,
			fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			if ${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			for i := range c.${fieldName} {
				${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
				${selector}AppendInt(&w, int64(${genericTypeCast}(&c.${fieldName}[i]).CachedCanotoSize()))
				w = ${genericTypeCast}(&c.${fieldName}[i]).MarshalCanotoInto(w)
			}
		}
	}
`,
		},
		pointers: typeTemplate{
			single: `	if c.${fieldName} != nil {
		if fieldSize := ${genericTypeCast}(c.${fieldName}).CachedCanotoSize(); fieldSize != 0 {
			${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
			${selector}AppendInt(&w, int64(fieldSize))
			w = ${genericTypeCast}(c.${fieldName}).MarshalCanotoInto(w)
		}
	}
`,
			repeated: `	for i := range c.${fieldName} {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		var fieldSize int
		if c.${fieldName}[i] != nil {
			fieldSize = ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize()
		}
		${selector}AppendInt(&w, int64(fieldSize))
		if fieldSize != 0 {
			w = ${genericTypeCast}(c.${fieldName}[i]).MarshalCanotoInto(w)
		}
	}
`,
			fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			if c.${fieldName}[i] != nil && ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			for i := range c.${fieldName} {
				${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
				var fieldSize int
				if c.${fieldName}[i] != nil {
					fieldSize = ${genericTypeCast}(c.${fieldName}[i]).CachedCanotoSize()
				}
				${selector}AppendInt(&w, int64(fieldSize))
				if fieldSize != 0 {
					w = ${genericTypeCast}(c.${fieldName}[i]).MarshalCanotoInto(w)
				}
			}
		}
	}
`,
		},
		fields: typeTemplate{
			single: `	if fieldSize := c.${fieldName}.CachedCanotoSize(); fieldSize != 0 {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		${selector}AppendInt(&w, int64(fieldSize))
		w = c.${fieldName}.MarshalCanotoInto(w)
	}
`,
			repeated: `	for i := range c.${fieldName} {
		${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		fieldSize := c.${fieldName}[i].CachedCanotoSize()
		${selector}AppendInt(&w, int64(fieldSize))
		if fieldSize != 0 {
			w = c.${fieldName}[i].MarshalCanotoInto(w)
		}
	}
`,
			fixedRepeated: `	{
		isZero := true
		for i := range c.${fieldName} {
			if c.${fieldName}[i].CachedCanotoSize() != 0 {
				isZero = false
				break
			}
		}
		if !isZero {
			for i := range c.${fieldName} {
				${selector}Append(&w, canoto__${escapedStructName}__${escapedFieldName}__tag)
				fieldSize := c.${fieldName}[i].CachedCanotoSize()
				${selector}AppendInt(&w, int64(fieldSize))
				if fieldSize != 0 {
					w = c.${fieldName}[i].MarshalCanotoInto(w)
				}
			}
		}
	}
`,
		},
	})
}

type messageTemplate struct {
	ints    typeTemplate
	fints   typeTemplate
	bools   typeTemplate
	strings typeTemplate

	bytesTemplate                   string
	repeatedBytesTemplate           string
	fixedBytesTemplate              string
	repeatedFixedBytesTemplate      string
	fixedRepeatedBytesTemplate      string
	fixedRepeatedFixedBytesTemplate string

	values   typeTemplate
	pointers typeTemplate
	fields   typeTemplate
}

type typeTemplate struct {
	single        string
	repeated      string
	fixedRepeated string
}

func writeMessage(m message, t messageTemplate) string {
	var s strings.Builder
	for _, f := range m.fields {
		_ = writeField(&s, f, t)
	}
	return s.String()
}

func writeField(w io.Writer, f field, t messageTemplate) error {
	var template string
	switch c := f.canotoType; c {
	case canotoInt, canotoSint:
		template = t.ints.single
	case canotoRepeatedInt, canotoRepeatedSint:
		template = t.ints.repeated
	case canotoFixedRepeatedInt, canotoFixedRepeatedSint:
		template = t.ints.fixedRepeated
	case canotoFint32, canotoFint64:
		template = t.fints.single
	case canotoRepeatedFint32, canotoRepeatedFint64:
		template = t.fints.repeated
	case canotoFixedRepeatedFint32, canotoFixedRepeatedFint64:
		template = t.fints.fixedRepeated
	case canotoBool:
		template = t.bools.single
	case canotoRepeatedBool:
		template = t.bools.repeated
	case canotoFixedRepeatedBool:
		template = t.bools.fixedRepeated
	case canotoString:
		template = t.strings.single
	case canotoRepeatedString:
		template = t.strings.repeated
	case canotoFixedRepeatedString:
		template = t.strings.fixedRepeated
	case canotoBytes:
		template = t.bytesTemplate
	case canotoFixedBytes:
		template = t.fixedBytesTemplate
	case canotoRepeatedBytes:
		template = t.repeatedBytesTemplate
	case canotoRepeatedFixedBytes:
		template = t.repeatedFixedBytesTemplate
	case canotoFixedRepeatedBytes:
		template = t.fixedRepeatedBytesTemplate
	case canotoFixedRepeatedFixedBytes:
		template = t.fixedRepeatedFixedBytesTemplate
	case canotoValue:
		template = t.values.single
	case canotoRepeatedValue:
		template = t.values.repeated
	case canotoFixedRepeatedValue:
		template = t.values.fixedRepeated
	case canotoPointer:
		template = t.pointers.single
	case canotoRepeatedPointer:
		template = t.pointers.repeated
	case canotoFixedRepeatedPointer:
		template = t.pointers.fixedRepeated
	case canotoField:
		template = t.fields.single
	case canotoRepeatedField:
		template = t.fields.repeated
	default:
		template = t.fields.fixedRepeated
	}
	return writeTemplate(w, template, f.templateArgs)
}

func writeTemplate(w io.Writer, template string, args map[string]string) error {
	s := os.Expand(template, func(key string) string {
		return args[key]
	})
	_, err := w.Write([]byte(s))
	return err
}
