package generate

import (
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/StephenButtolph/canoto"
)

const repeated = true

func write(w io.Writer, packageName string, messages []message) error {
	const fileTemplate = `// Code generated by Canoto. DO NOT EDIT.

package ${package}

import (
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that "unicode/utf8" is imported without error
var _ = utf8.ValidString
`
	err := writeTemplate(w, fileTemplate, map[string]string{
		"package": packageName,
	})
	if err != nil {
		return err
	}

	for _, m := range messages {
		if err := writeStruct(w, m); err != nil {
			return err
		}
	}
	return nil
}

func writeStruct(w io.Writer, m message) error {
	const structTemplate = `
const (
${tagConstants}
${tagSizeConstants})

type canotoData_${structName} struct {
	size int
${cache}}

func (c *${structName}) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(&r)
}

func (c *${structName}) UnmarshalCanotoFrom(r *canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(r) {
		field, wireType, err := canoto.ReadTag(r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
${unmarshal}		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

func (c *${structName}) ValidCanoto() bool {
${valid}	return true
}

func (c *${structName}) CalculateCanotoSize() int {
	c.canotoData.size = 0
${size}	return c.canotoData.size
}

func (c *${structName}) CachedCanotoSize() int {
	return c.canotoData.size
}

func (c *${structName}) MarshalCanoto() []byte {
	w := canoto.Writer{
		B: make([]byte, 0, c.CalculateCanotoSize()),
	}
	c.MarshalCanotoInto(&w)
	return w.B
}

func (c *${structName}) MarshalCanotoInto(w *canoto.Writer) {
${marshal}}
`

	tagConstants, err := makeTagConstants(m)
	if err != nil {
		return err
	}
	unmarshal, err := makeUnmarshal(m)
	if err != nil {
		return err
	}
	size, err := makeSize(m)
	if err != nil {
		return err
	}
	marshal, err := makeMarshal(m)
	if err != nil {
		return err
	}

	return writeTemplate(w, structTemplate, map[string]string{
		"tagConstants":     tagConstants,
		"tagSizeConstants": makeTagSizeConstants(m),
		"structName":       m.name,
		"cache":            makeCache(m),
		"unmarshal":        unmarshal,
		"valid":            makeValid(m),
		"size":             size,
		"marshal":          marshal,
	})
}

func makeTagConstants(m message) (string, error) {
	var s strings.Builder
	for _, f := range m.fields {
		_, _ = fmt.Fprintf(
			&s,
			`	canoto__%s__%s__tag = "`,
			m.canonicalizedName,
			f.canonicalizedName,
		)

		wireType, err := f.WireType()
		if err != nil {
			return "", err
		}

		tagBytes := canoto.Tag(f.fieldNumber, wireType)
		tagHex := hex.EncodeToString(tagBytes)
		for i := 0; i < len(tagHex); i += 2 {
			_, _ = fmt.Fprintf(&s, "\\x%s", tagHex[i:i+2])
		}
		_, _ = fmt.Fprintf(
			&s,
			"\" // canoto.Tag(%d, canoto.%s)\n",
			f.fieldNumber,
			wireType,
		)
	}
	return s.String(), nil
}

func makeTagSizeConstants(m message) string {
	var s strings.Builder
	for _, f := range m.fields {
		_, _ = fmt.Fprintf(
			&s,
			"\tcanoto__%s__%s__tag__size = len(canoto__%s__%s__tag)\n",
			m.canonicalizedName,
			f.canonicalizedName,
			m.canonicalizedName,
			f.canonicalizedName,
		)
	}
	return s.String()
}

func makeCache(m message) string {
	var s strings.Builder
	for _, f := range m.fields {
		if !f.repeated || !f.canotoType.IsVarint() {
			continue
		}

		_, _ = fmt.Fprintf(
			&s,
			"\t%sSize int\n",
			f.name,
		)
	}
	return s.String()
}

func makeUnmarshal(m message) (string, error) {
	const (
		intTemplate = `		case ${fieldNumber}:
			if wireType != canoto.${wireType} {
				return canoto.ErrInvalidWireType
			}
			c.${fieldName}, err = canoto.Read${readFunction}(r)
			if err != nil {
				return err
			}
			if canoto.IsZero(c.${fieldName}) {
				return canoto.ErrZeroValue
			}
`
		repeatedIntTemplate = `		case ${fieldNumber}:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			msgBytes, err := canoto.ReadBytes(r)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}

			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = make([]${goType}, 0, canoto.CountInts(msgBytes))
			for canoto.HasNext(r) {
				v, err := canoto.Read${readFunction}(r)
				if err != nil {
					r.B = remainingBytes
					return err
				}
				c.${fieldName} = append(c.${fieldName}, v)
			}
			r.B = remainingBytes
`
		repeatedFixedSizeTemplate = `		case ${fieldNumber}:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			msgBytes, err := canoto.ReadBytes(r)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}
			numMsgBytes := len(msgBytes)
			if numMsgBytes == 0 {
				return canoto.ErrZeroValue
			}

			remainingBytes := r.B
			r.B = msgBytes
			c.${fieldName} = make([]${goType}, 0, numMsgBytes/canoto.Size${sizeConstant})
			for canoto.HasNext(r) {
				v, err := canoto.Read${readFunction}(r)
				if err != nil {
					r.B = remainingBytes
					return err
				}
				c.${fieldName} = append(c.${fieldName}, v)
			}
			r.B = remainingBytes
`
		bytesTemplate = `		case ${fieldNumber}:
			if wireType != canoto.${wireType} {
				return canoto.ErrInvalidWireType
			}
			c.${fieldName}, err = canoto.Read${readFunction}(r)
			if err != nil {
				return err
			}
			if len(c.${fieldName}) == 0 {
				return canoto.ErrZeroValue
			}
`
		repeatedBytesTemplate = `		case ${fieldNumber}:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}

			v, err := canoto.Read${readFunction}(r)
			if err != nil {
				return err
			}

			count, err := canoto.CountBytes(r.B, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = make([]${goType}, 1, 1+count)
			c.${fieldName}[0] = v
			for range count {
				r.B = r.B[canoto__${escapedStructName}__${escapedFieldName}__tag__size:]
				v, err := canoto.Read${readFunction}(r)
				if err != nil {
					return err
				}
				c.${fieldName} = append(c.${fieldName}, v)
			}
`
		customTemplate = `		case ${fieldNumber}:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			msgBytes, err := canoto.ReadBytes(r)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return canoto.ErrZeroValue
			}

			remainingBytes := r.B
			r.B = msgBytes
			err = c.${fieldName}.UnmarshalCanotoFrom(r)
			r.B = remainingBytes
			if err != nil {
				return err
			}
`
		repeatedCustomTemplate = `		case ${fieldNumber}:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}

			originalUnsafe := r.Unsafe
			r.Unsafe = true
			msgBytes, err := canoto.ReadBytes(r)
			r.Unsafe = originalUnsafe
			if err != nil {
				return err
			}

			remainingBytes := r.B
			count, err := canoto.CountBytes(remainingBytes, canoto__${escapedStructName}__${escapedFieldName}__tag)
			if err != nil {
				return err
			}

			c.${fieldName} = make([]${goType}, 1+count)
			r.B = msgBytes
			err = c.${fieldName}[0].UnmarshalCanotoFrom(r)
			r.B = remainingBytes
			if err != nil {
				return err
			}

			for i := range count {
				r.B = r.B[canoto__${escapedStructName}__${escapedFieldName}__tag__size:]
				r.Unsafe = true
				msgBytes, err := canoto.ReadBytes(r)
				r.Unsafe = originalUnsafe
				if err != nil {
					return err
				}

				remainingBytes := r.B
				r.B = msgBytes
				err = c.${fieldName}[1+i].UnmarshalCanotoFrom(r)
				r.B = remainingBytes
				if err != nil {
					return err
				}
			}
`
	)
	var (
		intTemplates = map[bool]string{
			!repeated: intTemplate,
			repeated:  repeatedIntTemplate,
		}
		fixedSizeTemplates = map[bool]string{
			!repeated: intTemplate,
			repeated:  repeatedFixedSizeTemplate,
		}
		bytesTemplates = map[bool]string{
			!repeated: bytesTemplate,
			repeated:  repeatedBytesTemplate,
		}
		customTemplates = map[bool]string{
			!repeated: customTemplate,
			repeated:  repeatedCustomTemplate,
		}
		s strings.Builder
	)
	for _, f := range m.fields {
		var template string
		switch f.canotoType {
		case canotoInt, canotoSint:
			template = intTemplates[f.repeated]
		case canotoFint, canotoBool:
			template = fixedSizeTemplates[f.repeated]
		case canotoBytes:
			switch f.goType {
			case goString, goBytes:
				template = bytesTemplates[f.repeated]
			default:
				template = customTemplates[f.repeated]
			}
		default:
			return "", fmt.Errorf("%w: %q", errUnexpectedCanotoType, f.canotoType)
		}
		_ = writeTemplate(&s, template, f.templateArgs)
	}
	return s.String(), nil
}

func makeValid(m message) string {
	const (
		stringTemplate = `	if !utf8.ValidString(c.${fieldName}) {
		return false
	}
`
		repeatedStringTemplate = `	for _, v := range c.${fieldName} {
		if !utf8.ValidString(v) {
			return false
		}
	}
`
		customTemplate = `	if !c.${fieldName}.ValidCanoto() {
		return false
	}
`
		repeatedCustomTemplate = `	for i := range c.${fieldName} {
		if !c.${fieldName}[i].ValidCanoto() {
			return false
		}
	}
`
	)
	var (
		stringTemplates = map[bool]string{
			!repeated: stringTemplate,
			repeated:  repeatedStringTemplate,
		}
		customTemplates = map[bool]string{
			!repeated: customTemplate,
			repeated:  repeatedCustomTemplate,
		}
		s strings.Builder
	)
	for _, f := range m.fields {
		if f.canotoType != canotoBytes || f.goType == goBytes {
			continue
		}

		// goType is either string or a custom type
		var template string
		if f.goType == goString {
			template = stringTemplates[f.repeated]
		} else {
			template = customTemplates[f.repeated]
		}
		_ = writeTemplate(&s, template, map[string]string{
			"fieldName": f.name,
		})
	}
	return s.String()
}

func makeSize(m message) (string, error) {
	const (
		intTemplate = `	if !canoto.IsZero(c.${fieldName}) {
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.Size${sizeFunction}(c.${fieldName})
	}
`
		repeatedIntTemplate = `	if len(c.${fieldName}) != 0 {
		c.canotoData.${fieldName}Size = 0
		for _, v := range c.${fieldName} {
			c.canotoData.${fieldName}Size += canoto.Size${sizeFunction}(v)
		}
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeInt(int64(c.canotoData.${fieldName}Size)) + c.canotoData.${fieldName}Size
	}
`
		fixedSizeTemplate = `	if !canoto.IsZero(c.${fieldName}) {
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.Size${sizeConstant}
	}
`
		repeatedFixedSizeTemplate = `	if num := len(c.${fieldName}); num != 0 {
		fieldSize := num * canoto.Size${sizeConstant}
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
`
		bytesTemplate = `	if len(c.${fieldName}) != 0 {
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeBytes(c.${fieldName})
	}
`
		repeatedBytesTemplate = `	for _, v := range c.${fieldName} {
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeBytes(v)
	}
`
		customTemplate = `	if fieldSize := c.${fieldName}.CalculateCanotoSize(); fieldSize != 0 {
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
`
		repeatedCustomTemplate = `	for i := range c.${fieldName} {
		fieldSize := c.${fieldName}[i].CalculateCanotoSize()
		c.canotoData.size += canoto__${escapedStructName}__${escapedFieldName}__tag__size + canoto.SizeInt(int64(fieldSize)) + fieldSize
	}
`
	)
	var (
		intTemplates = map[bool]string{
			!repeated: intTemplate,
			repeated:  repeatedIntTemplate,
		}
		fixedSizeTemplates = map[bool]string{
			!repeated: fixedSizeTemplate,
			repeated:  repeatedFixedSizeTemplate,
		}
		bytesTemplates = map[bool]string{
			!repeated: bytesTemplate,
			repeated:  repeatedBytesTemplate,
		}
		customTemplates = map[bool]string{
			!repeated: customTemplate,
			repeated:  repeatedCustomTemplate,
		}
		s strings.Builder
	)
	for _, f := range m.fields {
		var template string
		switch f.canotoType {
		case canotoInt, canotoSint:
			template = intTemplates[f.repeated]
		case canotoFint, canotoBool:
			template = fixedSizeTemplates[f.repeated]
		case canotoBytes:
			switch f.goType {
			case goString, goBytes:
				template = bytesTemplates[f.repeated]
			default:
				template = customTemplates[f.repeated]
			}
		default:
			return "", fmt.Errorf("%w: %q", errUnexpectedCanotoType, f.canotoType)
		}
		_ = writeTemplate(&s, template, f.templateArgs)
	}
	return s.String(), nil
}

func makeMarshal(m message) (string, error) {
	const (
		intTemplate = `	if c.${fieldName} != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.Append${sizeFunction}(w, c.${fieldName})
	}
`
		repeatedIntTemplate = `	if len(c.${fieldName}) != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendInt(w, int64(c.canotoData.${fieldName}Size))
		for _, v := range c.${fieldName} {
			canoto.Append${sizeFunction}(w, v)
		}
	}
`
		fintTemplate = `	if c.${fieldName} != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.Append${sizeConstant}(w, c.${fieldName})
	}
`
		repeatedFixedSizeTemplate = `	if num := len(c.${fieldName}); num != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendInt(w, int64(num*canoto.Size${sizeConstant}))
		for _, v := range c.${fieldName} {
			canoto.Append${sizeConstant}(w, v)
		}
	}
`
		boolTemplate = `	if c.${fieldName} {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendBool(w, true)
	}
`
		bytesTemplate = `	if len(c.${fieldName}) != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendBytes(w, c.${fieldName})
	}
`
		repeatedBytesTemplate = `	for _, v := range c.${fieldName} {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendBytes(w, v)
	}
`
		customTemplate = `	if fieldSize := c.${fieldName}.CachedCanotoSize(); fieldSize != 0 {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendInt(w, int64(fieldSize))
		c.${fieldName}.MarshalCanotoInto(w)
	}
`
		repeatedCustomTemplate = `	for i := range c.${fieldName} {
		canoto.Append(w, canoto__${escapedStructName}__${escapedFieldName}__tag)
		canoto.AppendInt(w, int64(c.${fieldName}[i].CachedCanotoSize()))
		c.${fieldName}[i].MarshalCanotoInto(w)
	}
`
	)
	var (
		intTemplates = map[bool]string{
			!repeated: intTemplate,
			repeated:  repeatedIntTemplate,
		}
		fintTemplates = map[bool]string{
			!repeated: fintTemplate,
			repeated:  repeatedFixedSizeTemplate,
		}
		boolTemplates = map[bool]string{
			!repeated: boolTemplate,
			repeated:  repeatedFixedSizeTemplate,
		}
		bytesTemplates = map[bool]string{
			!repeated: bytesTemplate,
			repeated:  repeatedBytesTemplate,
		}
		customTemplates = map[bool]string{
			!repeated: customTemplate,
			repeated:  repeatedCustomTemplate,
		}
		s strings.Builder
	)
	for _, f := range m.fields {
		var template string
		switch f.canotoType {
		case canotoInt, canotoSint:
			template = intTemplates[f.repeated]
		case canotoFint:
			template = fintTemplates[f.repeated]
		case canotoBool:
			template = boolTemplates[f.repeated]
		case canotoBytes:
			switch f.goType {
			case goString, goBytes:
				template = bytesTemplates[f.repeated]
			default:
				template = customTemplates[f.repeated]
			}
		default:
			return "", fmt.Errorf("%w: %q", errUnexpectedCanotoType, f.canotoType)
		}
		_ = writeTemplate(&s, template, f.templateArgs)
	}
	return s.String(), nil
}

func writeTemplate(w io.Writer, template string, args map[string]string) error {
	s := os.Expand(template, func(key string) string {
		return args[key]
	})
	_, err := w.Write([]byte(s))
	return err
}
