// Code generated by Canoto. DO NOT EDIT.
// Source: internal/proto/examples/scalars.go

package examples

import (
	"github.com/StephenButtolph/canoto"
)

const (
	canoto__LargestFieldNumber__Int32__tag = "\xf8\xff\xff\xff\x0f" // canoto.Tag(536870911, canoto.Varint)

	canoto__LargestFieldNumber__Int32__tag__size = len(canoto__LargestFieldNumber__Int32__tag)
)

type canotoData_LargestFieldNumber struct{}

func (l *LargestFieldNumber) UnmarshalCanoto(r *canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(r) {
		field, wireType, err := canoto.ReadTag(r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 536870911:
			if wireType != canoto.Varint {
				return canoto.ErrInvalidWireType
			}
			l.Int32, err = canoto.ReadInt[int32](r)
		default:
			return canoto.ErrUnknownField
		}
		if err != nil {
			return err
		}

		minField = field + 1
	}
	return nil
}

func (l *LargestFieldNumber) ValidCanoto() bool {
	return true
}

func (l *LargestFieldNumber) SizeCanoto() int {
	var size int
	if l.Int32 != 0 {
		size += canoto__LargestFieldNumber__Int32__tag__size + canoto.SizeInt(l.Int32)
	}
	return size
}

func (l *LargestFieldNumber) MarshalCanoto(w *canoto.Writer) {
	if l.Int32 != 0 {
		canoto.Append(w, canoto__LargestFieldNumber__Int32__tag)
		canoto.AppendInt(w, l.Int32)
	}
}
